locals {
  azure_regions = {
    # Europe
    "northeurope"        = "eun"
    "westeurope"         = "euw"
    "francecentral"      = "frc"
    "francesouth"        = "frs"
    "germanywestcentral" = "dewc"
    "germanynorth"       = "den"
    "swedencentral"      = "swc"
    "swedensouth"        = "sws"
    "switzerlandnorth"   = "szn"
    "switzerlandwest"    = "szw"
    "norwayeast"         = "noe"
    "norwaywest"         = "now"
    "uksouth"            = "uks"
    "ukwest"             = "ukw"
    "spaincentral"       = "spc"
    "polandcentral"      = "plc"
    "italynorth"         = "itn"
    "denmarkeast"        = "dke"
    "belgiumcentral"     = "bec"
    "austriaeast"        = "ate"

    # Americas
    "eastus"          = "use"
    "eastus2"         = "use2"
    "centralus"       = "usc"
    "northcentralus"  = "usnc"
    "southcentralus"  = "ussc"
    "westus"          = "usw"
    "westus2"         = "usw2"
    "westus3"         = "usw3"
    "canadacentral"   = "cac"
    "canadaeast"      = "cae"
    "brazilsouth"     = "brs"
    "brazilsoutheast" = "brse"
    "mexicocentral"   = "mxc"
    "chilecentral"    = "clc"

    # Asia Pacific
    "eastasia"           = "ase"
    "southeastasia"      = "sea"
    "japaneast"          = "jpe"
    "japanwest"          = "jpw"
    "koreacentral"       = "krc"
    "koreasouth"         = "krs"
    "centralindia"       = "inc"
    "southindia"         = "sin"
    "westindia"          = "win"
    "indonesiacentral"   = "idc"
    "malaysiawest"       = "myw"
    "australiaeast"      = "aue"
    "australiasoutheast" = "aus"
    "australiacentral"   = "auc"
    "australiacentral2"  = "auc2"
    "newzealandnorth"    = "nzn"

    # Middle East & Africa
    "uaenorth"         = "uan"
    "uaecentral"       = "uac"
    "qatarcentral"     = "qac"
    "israelcentral"    = "ilc"
    "southafricanorth" = "san"
    "southafricawest"  = "saw"
  }

  hostpool_name = "hp-np-ei-tf-mp-${local.azure_regions[random_shuffle.region.result[0]]}-${random_integer.instance_index.result}"
  avd_vm_prefix = "${var.avd_vm_prefix}${local.azure_regions[random_shuffle.region.result[0]]}${random_integer.instance_index.result}"
}
